testeRestaurante/testeRestaurante/Models/Pedidos.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Web;

namespace testeRestaurante.Models
{
    public class Pedidos
    {
        public string Entrada { get; set; }
        public string PratoPrincipal { get; set; }
        public string Bebida { get; set; }
        public string Sobremesa { get; set; }

        public class JsonPedidos
        {
            public string Entrada { get; set; }
            public string PratoPrincipal { get; set; }
            public string Bebida { get; set; }
            public string Sobremesa { get; set; }
        }

        enum manha
        {
            [Description("Ovos")]
            Ovos = 1,
            [Description("Torradas")]
            Torradas = 2,
            [Description("Café")]
            Cafe = 3
        }
        enum noite
        {
            [Description("Bife")]
            Bife = 1,
            [Description("Batatas")]
            Batatas = 2,
            [Description("Vinho")]
            Vinho = 3,
            [Description("Bolo")]
            Bolo = 4
        }

        public List<string> ValidarPedido(string pedido)
        {
            List<string> _pedido = new List<string>(pedido.Split(','));
            List<string> oPedido = new List<string>();
            string periodo = _pedido.First();
            _pedido.Remove(_pedido.First());
            _pedido.Sort();
            _pedido = FormatarLista(_pedido);

            if (RemoverAcentos(periodo.ToLower()) == "manha")
            {
                oPedido = VerificarRepeticoes(_pedido, "manha");
            }
            else if(RemoverAcentos(periodo.ToLower()) == "noite")
            {
                oPedido = VerificarRepeticoes(_pedido, "noite");
            }

            return oPedido;
        }

        public static string RemoverAcentos(string texto)
        {
            string s = texto.Normalize(NormalizationForm.FormD);
            StringBuilder sb = new StringBuilder();
            for (int k = 0; k < s.Length; k++)
            {
                UnicodeCategory uc = CharUnicodeInfo.GetUnicodeCategory(s[k]);
                if (uc != UnicodeCategory.NonSpacingMark)
                {
                    sb.Append(s[k]);
                }
            }
            return sb.ToString();
        }

        public List<string> VerificarRepeticoes(List<string> Lista, string periodo)
        {
            List<string> Pedidos = new List<string>();

            if(periodo == "manha")
            {
                for(int i = 0; i < Lista.Count(); i++)
                {
                    if (Lista[i] == "1")
                    {
                        if (Pedidos.Contains(Enum.GetName(typeof(manha), 1).ToString()))
                        {
                            AdicionarItem(Pedidos, "erro");
                            break;
                        }
                        else
                        {
                            AdicionarItem(Pedidos, Enum.GetName(typeof(manha), Int32.Parse(Lista[i])));
                        }
                    }
                    else if(Lista[i] == "2")
                    {
                        if (Pedidos.Contains(Enum.GetName(typeof(manha), 2).ToString()))
                        {
                            AdicionarItem(Pedidos, "erro");
                            break;
                        }
                        else
                        {
                            AdicionarItem(Pedidos, Enum.GetName(typeof(manha), Int32.Parse(Lista[i])));
                        }
                    }
                    else
                    {
                        AdicionarItem(Pedidos, Enum.GetName(typeof(manha), Int32.Parse(Lista[i])));
                    }
                }

            }
            else if(periodo == "noite")
            {
                for (int i = 0; i < Lista.Count(); i++)
                {
                    if (Lista[i] == "1")
                    {
                        if (Pedidos.Contains(Enum.GetName(typeof(noite), 1).ToString()))
                        {
                            AdicionarItem(Pedidos, "erro");
                            break;
                        }
                        else
                        {
                            AdicionarItem(Pedidos, Enum.GetName(typeof(noite), Int32.Parse(Lista[i])));
                        }
                    }
                    else if (Lista[i] == "3")
                    {
                        if (Pedidos.Contains(Enum.GetName(typeof(noite), 3).ToString()))
                        {
                            AdicionarItem(Pedidos, "erro");
                            break;
                        }
                        else
                        {
                            AdicionarItem(Pedidos, Enum.GetName(typeof(noite), Int32.Parse(Lista[i])));
                        }
                    }
                    else if (Lista[i] == "4")
                    {
                        if (Pedidos.Contains(Enum.GetName(typeof(noite), 4).ToString()))
                        {
                            AdicionarItem(Pedidos, "erro");
                            break;
                        }
                        else
                        {
                            AdicionarItem(Pedidos, Enum.GetName(typeof(noite), Int32.Parse(Lista[i])));
                        }
                    }
                    else
                    {
                        AdicionarItem(Pedidos, Enum.GetName(typeof(noite), Int32.Parse(Lista[i])));
                    }
                }
            }
            else
            {
                throw new Exception("Período inválido");
            }

            return Pedidos;

        }

        public List<string> AdicionarItem(List<string>Lista, string item)
        {
            Lista.Add(item);

            return Lista;
        }

        public List<string> VerificarIntegridadePedido(List<string> Lista)
        {
            foreach (string item in Lista)
            {
                if (Int32.Parse(item) > 5)
                {
                    Lista.Add("erro");
                    break;
                }
            }

            return Lista;
        }

        public List<string> FormatarLista(List<string> Lista)
        {
            for(int i = 0; i < Lista.Count(); i++)
            {
                Lista[i] = Lista[i].Trim();
            }

            return Lista;
        }
    }
}

testeRestaurante/testeRestaurante/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace testeRestaurante.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            string path = Server.MapPath("~/JSON/pedidos.json");

            string jsonString = System.IO.File.ReadAllText(path);

            ViewData["pedido"] = jsonString;

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

testeRestaurante/testeRestaurante/Controllers/PedidosController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Text.Json;
using System.Text.Json.Serialization;
using testeRestaurante.Models;
using System.Text;
using System.Globalization;
using static testeRestaurante.Models.Pedidos;

namespace testeRestaurante.Controllers
{
    public class PedidosController : Controller
    {
        // GET: Pedidos
        public ActionResult Index()
        {
            return View();
        }

        // POST: Pedidos/Create
        [HttpPost]
        public ActionResult Create(string pedido)
        {
            string path = Server.MapPath("~/JSON/pedidos.json");

            try
            {
                Pedidos pedidos = new Pedidos();
                List<string> _pedido = new List<string>(pedidos.ValidarPedido(pedido));

                string PedidosJson = JsonSerializer.Serialize(_pedido);

                System.IO.File.WriteAllText(path, PedidosJson);

                return RedirectToAction("Index", "Home");
            }
            catch(Exception ex)
            {
                ex.ToString();
                return RedirectToAction("Index", "Home");
            }
        }
    }
}

testeRestaurante/testeRestaurante/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/_LayoutRestaurante.cshtml";
}

<!-- ======= Place your order Section ======= -->
<section id="place-your-order" class="book-a-table">
    <div class="container">

        <div class="section-title">
            <h2>Faça seu <span>Pedido</span></h2>
            <p>Faça e confira seus pedidos aqui.</p>
        </div>

        @using (Html.BeginForm("Create", "Pedidos", FormMethod.Post))
        {
            <div class="form-row">
                <div class="col-lg-12 col-md-12 form-group">
                    <input type="text" name="pedido" class="form-control" id="pedido" placeholder="Escolha seus itens" data-rule="minlen:4" data-msg="Please enter at least 4 chars">
                    <div class="validate"></div>
                </div>
            </div>
            <div class="text-center"><button type="submit">Enviar pedido</button></div>
        }

    </div>
    <br />
    <br />
    <div class="container">

        <div class="section-title">
            <h2>Último pedido</h2>
            <p>Confira seu último pedido.</p>
        </div>
        <form action="#">
            <div class="form-row">
                <div class="col-lg-12 col-md-12 form-group">
                    <input type="text" value="@ViewData["pedido"]" name="ultimoPedido" class="form-control" id="ultimoPedido" placeholder="Escolha seus itens" data-rule="minlen:4" data-msg="Please enter at least 4 chars">
                </div>
            </div>
        </form>

    </div>
</section><!-- End Book A Table Section -->
<script type="text/javascript">
    item = document.getElementById("ultimoPedido");

    pedido = item.value;
    pedido = pedido.split(',');
    for (var i = 0; i < pedido.length; i++)
    {
        pedido[i] = pedido[i].replace(/[^a-zA-Zs]/g, "");
    }

    item.value = pedido;
</script>

testeRestaurante/testeRestaurante/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nome do aplicativo", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Início", "Index", "Home")</li>
                    <li>@Html.ActionLink("Sobre", "About", "Home")</li>
                    <li>@Html.ActionLink("Contato", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Meu Aplicativo ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

testeRestaurante/testeRestaurante/Views/Shared/_LayoutRestaurante.cshtml
<!DOCTYPE html>
<html lang="pt-Br">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Delicious Bootstrap Template - Index</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="assets/img/favicon.png" rel="icon">
    <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,300i,400,400i,600,600i,700,700i|Satisfy|Comic+Neue:300,300i,400,400i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet">
        <link href="~/Content/icofont.min.css" rel="stylesheet">
        <link href="~/Content/boxicons.min.css" rel="stylesheet">
        <link href="~/Content/animate.min.css" rel="stylesheet">
        <link href="~/Content/venobox.css" rel="stylesheet">
        <link href="assets/vendor/owl.carousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/Content/style.css" rel="stylesheet">

    <!-- =======================================================
    * Template Name: Delicious - v2.2.1
    * Template URL: https://bootstrapmade.com/delicious-free-restaurant-bootstrap-theme/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
</head>

<body>

    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top d-flex align-items-center header-transparent">
        <div class="container d-flex align-items-center">

            <div class="logo mr-auto">
                <h1 class="text-light"><a href="index.html"><span>Delicious</span></a></h1>
                <!-- Uncomment below if you prefer to use an image logo -->
                <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
            </div>

            <nav class="nav-menu d-none d-lg-block">
                <ul>
                    <li class="active"><a href="index.html">Home</a></li>
                    <li><a href="#menu">Cardápio</a></li>
                    <li class="book-a-table text-center"><a href="#place-your-order">Faça seu pedido</a></li>
                </ul>
            </nav><!-- .nav-menu -->

        </div>
    </header><!-- End Header -->
    <section id="hero">
        <div class="hero-container">
            <div id="heroCarousel" class="carousel slide carousel-fade" data-ride="carousel">

                <ol class="carousel-indicators" id="hero-carousel-indicators"></ol>

                <div class="carousel-inner" role="listbox">

                    <!-- Slide 1 -->
                    <div class="carousel-item active" style="background: url(Assets/img/slide-1.jpg);">
                        <div class="carousel-container">
                            <div class="carousel-content">
                                <h2 class="animate__animated animate__fadeInDown"><span>Delicious</span> Restaurant</h2>
                                <p class="animate__animated animate__fadeInUp">Nosso delicioso restaurante possui opções de pratos para todas as refeições do dia. Sinta-se convidado a saborear nossas refeições.</p>
                                <div>
                                    <a href="#menu" class="btn-menu animate__animated animate__fadeInUp scrollto">Cardápio</a>
                                    <a href="#place-your-order" class="btn-book animate__animated animate__fadeInUp scrollto">Faça seu pedido</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section><!-- End Hero -->
    <!-- ======= Menu Section ======= -->
    <section id="menu" class="menu">
        <div class="container">

            <div class="section-title">
                <h2>Nosso <span>Cardápio</span></h2>
            </div>

            <div class="row menu-container">

                <div class="col-lg-6">
                    <div class="col-lg-6">
                        <h3>Opções da manhã</h3>
                    </div>

                    <div class="col-lg-6 menu-item">
                        <div class="menu-content">
                            <a href="#">1 (Entrada) - Ovos</a><span>$5.95</span>
                        </div>
                        <div class="menu-ingredients">
                            Ovos fritos ou mexidos
                        </div>
                    </div>

                    <div class="col-lg-6 menu-item">
                        <div class="menu-content">
                            <a href="#">2 (Prato principal) - Torradas</a><span>$6.95</span>
                        </div>
                        <div class="menu-ingredients">
                            Torradas integrais ou não
                        </div>
                    </div>

                    <div class="col-lg-6 menu-item">
                        <div class="menu-content">
                            <a href="#">3 (Bebida) - Café à vontade</a><span>$7.95</span>
                        </div>
                        <div class="menu-ingredients">
                            Nossos clientes têm direito ao café da casa à vontade
                        </div>
                    </div>
                    <br />
                    <div class="col-lg-6">
                        <h5>*Nas refeições da manhã não servimos sobremesa</h5>
                    </div>
                </div>

                <div class="col-lg-6">
                    <div class="col-lg-6">
                        <h3>Opções da noite</h3>
                    </div>

                    <div class="col-lg-6 menu-item">
                        <div class="menu-content">
                            <a href="#">1 (Entrada) - Bife</a><span>$8.95</span>
                        </div>
                        <div class="menu-ingredients">
                            Bife ao ponto ou bem passado
                        </div>
                    </div>

                    <div class="col-lg-6 menu-item">
                        <div class="menu-content">
                            <a href="#">2 (Prato principal) - Batatas à vontade</a><span>$9.95</span>
                        </div>
                        <div class="menu-ingredients">
                            Fritas á vontade. Coma o quanto puder
                        </div>
                    </div>

                    <div class="col-lg-6 menu-item">
                        <div class="menu-content">
                            <a href="#">3 (Bebida) - Vinho</a><span>$10.95</span>
                        </div>
                        <div class="menu-ingredients">
                            Vinho tinto ou branco
                        </div>
                    </div>

                    <div class="col-lg-6 menu-item">
                        <div class="menu-content">
                            <a href="#">4 (Sobremesa) - Bolo</a><span>$11.95</span>
                        </div>
                        <div class="menu-ingredients">
                            Bolo de chocolate ou fubá
                        </div>
                    </div>
                </div>

            </div>

        </div>
    </section><!-- End Menu Section -->
    <div>
        @RenderBody()
    </div>
</body>
</html>